### ISSUE TITLE
Cannot build using Swift 2.0 xcode 7

### ISSUE THREAD

**Issue by solomon23** [Thomvis/BrightFutures#83]
I keep seeing this compile crashes:

        Undefined symbols for architecture x86_64:
          "direct generic type metadata pattern for Result.Result", referenced from:
              type metadata accessor for Result.Result<Swift.String, BrightFutures.NoError> in Track.o
          "protocol witness table for <A, B where B: Swift.ErrorType> Result.Result<A, B> : Result.ResultType in Result", referenced from:
              static UpshotCore.Track.(demographicData in _355BED5052E6A82D51CFE2CBBD95410A) (UpshotCore.Track.Type)(Swift.String) -> () in Track.o
        ld: symbol(s) not found for architecture x86_64
        clang: error: linker command failed with exit code 1 (use -v to see invocation)

Even when I'm just using test code:

    func doStuff() -> Future<String, NoError> {
        let promise = Promise<String, NoError>()

        promise.success("hi")
        
        return promise.future
    }

**Comment by yonaskolb** [comment]
I was experiencing the same and manually had to add Result to my podfile
pod 'Result', '0.6-beta.1'

**Comment by solomon23** [comment]
Ah.  Nice.  I ended up moving to FutureKit.  Doesn't seem like a Promise library should need external dependencies.

**Comment by Thomvis** [comment]
Sorry to hear you were having problems and thanks @yonaskolb for the help! I will update the readme accordingly.

The reason why I use the Result dependency is to improve interoperability with other libraries that also use that Result type. Also, I'd say the burden of having an additional dependency is almost nonexistent when using Carthage or CocoaPods. Except if you run into errors of course :(

Whichever futures library you choose, I hope it works out well. Good luck!

**Comment by kurko** [comment]
Hey @Thomvis, you said you were going to update the README. Did you get a chance to do that? I didn't find anything related to this. Basically, I spent quite some time before I found this issue, so I think it makes sense to have it there.

**Comment by kurko** [comment]
Related https://github.com/Thomvis/BrightFutures/issues/81

**Comment by blg-nb** [comment]
I have the same error, but i can't solve it.
Please help me ...

**Comment by Thomvis** [comment]
Sorry that you're having problems. I have not encountered this error myself, so I'll need your help to fix the issue. 

Can you share your CocoaPods / Carthage file? Even better: could you create the smallest project that has this error?

Thanks

**Comment by kurko** [comment]
@big-nb FYI, I was using https://github.com/wvteijlingen/Spine, which requires BrightFutures and was loading `Result` lib as an extension. After https://github.com/wvteijlingen/Spine/commit/b5b9c559f7814c7919a044c50f760cfd180265c6, the error stopped. So the issue was not BrightFutures, but Spine.

**Comment by yonaskolb** [comment]
Maybe that's why mine is failing, because Alamofire also has a result class

**Comment by jstotz** [comment]
I ran into the same error using BrightFutures with Alamofire via Carthage was able to resolve it by adding an explicit `import Result`.

**Comment by christopher-prince** [comment]
I was running into a similar error, but removing the DerivedData files/folders made it go away.
