### ISSUE TITLE
Master doesn't compile on XCode 6.1.1 / Swift 1.1  due to default context parameters

### ISSUE THREAD

**Issue by tmu** [Thomvis/BrightFutures#31]
I get following 4 errors when compiling the latest master (6e4ca98b3f324a609e20267e76fe152397bbe469) on XCode 6.1.1 / Swift 1.1

```
/Users/teemu/all/flancer/protos/BrightFutures/BrightFutures/FutureUtils.swift:63:33: error: missing argument for parameter 'f' in call
            return zero.flatMap { zeroVal in

/Users/teemu/all/flancer/protos/BrightFutures/BrightFutures/Future.swift:261:24: error: missing argument for parameter 'callback' in call
        self.onFailure { err in
                       ^
/Users/teemu/all/flancer/protos/BrightFutures/BrightFutures/Future.swift:434:29: error: missing argument for parameter 'f' in call
        return self.flatMap { thisVal -> Future<(T,U)> in
                            ^
/Users/teemu/all/flancer/protos/BrightFutures/BrightFutures/Future.swift:442:29: error: missing argument for parameter 'f' in call
        return self.flatMap { value -> Result<T> in
```

**Comment by tmu** [comment]
These are caused by Swift 1.2 overload changes in e38a69c1ff1727d55eb35ca78365c754c03eb5c1

As you can't submit apps written with Swift 1.2 to App Store (only official XCode and GM Seed versions can be used for App Store submissions, not XCode Beta, and those will be likely available earliest in April-June), I would keep the master branch compatible with the official Swift 1.1 and have a separate 1.2 branch.

**Comment by Thomvis** [comment]
I agree that breaking Swift 1.1 support on the master branch is not good. It was a bad decision on my part, sorry about that. 

It should be like you suggest: the master branch should be compatible with the latest public release of Swift, there can be branches to support a beta or a previous version (e.g. 1.1 as soon as 1.2 comes out).

I'm not sure if I'll have the time to do this soon, so feel free to start on a pull request restoring Swift 1.1 support to the master, if you want (and seem to be suggesting in #12). Thanks!

**Comment by tmu** [comment]
I did the minimal work for porting master back to Swift 1.1. Please review and suggest if any further changes are needed. I think it's wiser to leave setting up the swift1.2 branch to you.
