### PR TITLE
Back to swift 1.1

### LINKED ISSUE #31: Master doesn't compile on XCode 6.1.1 / Swift 1.1  due to default context parameters
I get following 4 errors when compiling the latest master (6e4ca98b3f324a609e20267e76fe152397bbe469) on XCode 6.1.1 / Swift 1.1

```
/Users/teemu/all/flancer/protos/BrightFutures/BrightFutures/FutureUtils.swift:63:33: error: missing argument for parameter 'f' in call
            return zero.flatMap { zeroVal in

/Users/teemu/all/flancer/protos/BrightFutures/BrightFutures/Future.swift:261:24: error: missing argument for parameter 'callback' in call
        self.onFailure { err in
                       ^
/Users/teemu/all/flancer/protos/BrightFutures/BrightFutures/Future.swift:434:29: error: missing argument for parameter 'f' in call
        return self.flatMap { thisVal -> Future<(T,U)> in
                            ^
/Users/teemu/all/flancer/protos/BrightFutures/BrightFutures/Future.swift:442:29: error: missing argument for parameter 'f' in call
        return self.flatMap { value -> Result<T> in
```

### PR DESCRIPTION
**Pull request by tmu**
This is a minimal set of changes to get current master to compile on official XCode 6.1.1 and Swift 1.1. 

Fixes #31 and as described in the issue report I suggest that Swift 1.2 support is moved to a separate branch and master branch works against official XCode version.

Not tested extensively, but logic tests pass on a simulator and a real project that was previously using 1.0.0.beta2 compiles and works against this branch both in a simulator and a device. (compiled with XCode Version 6.1.1 (6A2008a) and Swift 1.1.)

### CODE REVIEW

**Comment by Thomvis** [comment]
Looks good, thanks! :+1:

`master` is now compatible with Swift 1.1 again. I've created a `swift1.2` branch that I will keep up to date with the coming beta's.
